
spring:
  cloud:
    azure:
# Properties like spring.cloud.azure.credential.client-id are global properties.
# Properties like spring.cloud.azure.active-directory.credential.client-id are AAD properties.
# If AAD properties is not configured, global properties will be used.
#      credential:
#        client-id:
      active-directory:
        enabled: true
        credential:
          client-id: ab8932fc-4f94-4d81-bc8a-f9e4ffd3e48c
        session-stateless: true
        app-id-uri: api://ab8932fc-4f94-4d81-bc8a-f9e4ffd3e48c


